In [1]:
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import Imputer
import numpy as np
from sklearn.cross_validation import train_test_split

C:\Users\USER\Anaconda3\envs\keras_env\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\USER\Anaconda3\envs\keras_env\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

# Reading the dataset

In [2]:
hcc = pd.read_csv("hcc-data.csv")

In [3]:
hcc.head(n=2)

,Gender,Symptoms,Alcohol,Hepatitis B Surface Antigen,Hepatitis B e Antigen,Hepatitis B Core Antibody,Hepatitis C Virus Antibody,Cirrhosis,Endemic Countries,Smoking,...,Alkaline phosphatase,Total Proteins,Creatinine,Number of Nodules,Major dimension of nodule,Direct Bilirubin,Iron,Oxygen Saturation,Ferritin,Class
0,0,1.0,0,0.0,0.0,0.0,0.0,1,0.0,0.0,...,104.0,5.4,0.60,5.0,7.8,0.2,46.0,18.0,NaN,0
1,1,NaN,1,0.0,NaN,1.0,0.0,1,0.0,1.0,...,113.0,7.8,0.55,2.0,6.2,0.3,94.0,33.0,393.0,1

In [4]:
hcc.columns

Index(['Gender', 'Symptoms', 'Alcohol', 'Hepatitis B Surface Antigen',
       'Hepatitis B e Antigen', 'Hepatitis B Core Antibody',
       'Hepatitis C Virus Antibody', 'Cirrhosis', 'Endemic Countries',
       'Smoking', 'Diabetes', 'Obesity', 'Hemochromatosis',
       'Arterial Hypertension', 'Chronic Renal Insufficiency',
       'Human Immunodeficiency Virus', 'Nonalcoholic Steatohepatitis',
       'Esophageal Varices', 'Splenomegaly', 'Portal Hypertension',
       'Portal Vein Thrombosis', 'Liver Metastasis', 'Radiological Hallmark',
       'Age_at_diagnosis', 'Grams of Alcohol per day',
       'Packs of cigarets per year', 'Performance Status',
       'Encefalopathy degree', 'Ascites degree',
       'International Normalised Ratio', 'Alpha-Fetoprotein', 'Haemoglobin',
       'Mean Corpuscular Volume', 'Leukocytes', 'Platelets', 'Albumin',
       'Total Bilirubin', 'Alanine transaminase', 'Aspartate transaminase',
       'Gamma glutamyl transferase', 'Alkaline phosphatase', 'Total Proteins',
       'Creatinine', 'Number of Nodules', 'Major dimension of nodule',
       'Direct Bilirubin', 'Iron', 'Oxygen Saturation', 'Ferritin', 'Class'],
      dtype='object')

# Handling the values for continuous attributes

In [5]:
continuous_x = hcc.iloc[:,23:49]

In [6]:
continuous_x.head()

,Age_at_diagnosis,Grams of Alcohol per day,Packs of cigarets per year,Performance Status,Encefalopathy degree,Ascites degree,International Normalised Ratio,Alpha-Fetoprotein,Haemoglobin,Mean Corpuscular Volume,...,Gamma glutamyl transferase,Alkaline phosphatase,Total Proteins,Creatinine,Number of Nodules,Major dimension of nodule,Direct Bilirubin,Iron,Oxygen Saturation,Ferritin
0,40,0.0,0.0,2,1.0,1.0,1.17,3.1,15.1,86.0,...,23.0,104.0,5.4,0.60,5.0,7.8,0.2,46.0,18.0,NaN
1,68,60.0,NaN,0,1.0,1.0,1.34,13.0,15.6,93.0,...,275.0,113.0,7.8,0.55,2.0,6.2,0.3,94.0,33.0,393.0
2,63,100.0,0.0,0,1.0,1.0,2.07,1.7,9.5,99.2,...,134.0,113.0,37.0,0.40,1.0,2.7,0.2,94.0,37.0,48.0
3,72,100.0,0.0,0,1.0,2.0,1.30,249.0,12.7,100.3,...,40.0,108.0,5.8,0.90,5.0,8.0,1.2,37.0,17.0,419.0
4,88,80.0,0.0,2,2.0,3.0,1.27,66.0,10.9,97.3,...,179.0,260.0,5.9,NaN,5.0,3.0,1.3,15.0,17.0,639.0

In [7]:
y_value = hcc.iloc[: , 49]

In [8]:
type(y_value)

pandas.core.series.Series

In [9]:
imputer = Imputer(missing_values = "NaN" ,strategy = 'mean', axis = 0)

In [10]:
imputer = imputer.fit(continuous_x)

In [11]:
continuous_x = imputer.transform(continuous_x)

In [12]:
print(continuous_x)

[[ 40.           0.           0.         ...  46.          18.
  443.70843672]
 [ 68.          60.          20.7235239  ...  94.          33.
  393.        ]
 [ 63.         100.           0.         ...  94.          37.
   48.        ]
 ...
 [ 77.          75.           0.         ...  85.75307125  37.28873134
  443.70843672]
 [ 75.           0.           0.         ...  85.75307125  37.28873134
  443.70843672]
 [ 55.         100.          20.7235239  ...  85.75307125  37.28873134
  443.70843672]]

In [13]:
continuous_x = pd.DataFrame(data = continuous_x)

In [14]:
continuous_x = continuous_x.apply(lambda x: (x - x.min()) / (x.max() - x.min()))

In [15]:
continuous_x.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,0.273973,0.00,0.000000,0.5,0.0,0.0,0.082915,1.049524e-06,0.737226,0.329341,...,0.000000,0.104953,0.015291,0.054054,1.0,0.307317,0.003425,0.205357,0.142857,0.198972
1,0.657534,0.12,0.040634,0.0,0.0,0.0,0.125628,6.518095e-06,0.773723,0.469062,...,0.162371,0.114149,0.039755,0.047297,0.4,0.229268,0.006849,0.419643,0.261905,0.176233
2,0.589041,0.20,0.000000,0.0,0.0,0.0,0.309045,2.761905e-07,0.328467,0.592814,...,0.071521,0.114149,0.337411,0.027027,0.2,0.058537,0.003425,0.419643,0.293651,0.021525
3,0.712329,0.20,0.000000,0.0,0.0,0.5,0.115578,1.368800e-04,0.562044,0.614770,...,0.010954,0.109040,0.019368,0.094595,1.0,0.317073,0.037671,0.165179,0.134921,0.187892
4,0.931507,0.16,0.000000,0.5,0.5,1.0,0.108040,3.579429e-05,0.430657,0.554890,...,0.100515,0.264345,0.020387,0.125969,1.0,0.073171,0.041096,0.066964,0.134921,0.286547

In [16]:
#X_train, X_test, y_train, y_test = train_test_split(continuous_x,y_value,test_size=0.3, random_state=100)

In [17]:
#X_train.columns = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

continuous_x.columns = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

#X_test.columns = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

In [18]:
continuous_x.head()

,a,b,c,d,e,f,g,h,i,j,...,q,r,s,t,u,v,w,x,y,z
0,0.273973,0.00,0.000000,0.5,0.0,0.0,0.082915,1.049524e-06,0.737226,0.329341,...,0.000000,0.104953,0.015291,0.054054,1.0,0.307317,0.003425,0.205357,0.142857,0.198972
1,0.657534,0.12,0.040634,0.0,0.0,0.0,0.125628,6.518095e-06,0.773723,0.469062,...,0.162371,0.114149,0.039755,0.047297,0.4,0.229268,0.006849,0.419643,0.261905,0.176233
2,0.589041,0.20,0.000000,0.0,0.0,0.0,0.309045,2.761905e-07,0.328467,0.592814,...,0.071521,0.114149,0.337411,0.027027,0.2,0.058537,0.003425,0.419643,0.293651,0.021525
3,0.712329,0.20,0.000000,0.0,0.0,0.5,0.115578,1.368800e-04,0.562044,0.614770,...,0.010954,0.109040,0.019368,0.094595,1.0,0.317073,0.037671,0.165179,0.134921,0.187892
4,0.931507,0.16,0.000000,0.5,0.5,1.0,0.108040,3.579429e-05,0.430657,0.554890,...,0.100515,0.264345,0.020387,0.125969,1.0,0.073171,0.041096,0.066964,0.134921,0.286547

# Handling the values for nominal values

In [19]:
nom_x = hcc.iloc[:,0:23]

In [20]:
nom_x.head()

,Gender,Symptoms,Alcohol,Hepatitis B Surface Antigen,Hepatitis B e Antigen,Hepatitis B Core Antibody,Hepatitis C Virus Antibody,Cirrhosis,Endemic Countries,Smoking,...,Arterial Hypertension,Chronic Renal Insufficiency,Human Immunodeficiency Virus,Nonalcoholic Steatohepatitis,Esophageal Varices,Splenomegaly,Portal Hypertension,Portal Vein Thrombosis,Liver Metastasis,Radiological Hallmark
0,0,1.0,0,0.0,0.0,0.0,0.0,1,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0
1,1,NaN,1,0.0,NaN,1.0,0.0,1,0.0,1.0,...,0.0,0.0,0.0,0.0,NaN,1.0,1.0,0.0,0.0,1.0
2,1,1.0,1,0.0,0.0,1.0,0.0,1,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
3,1,1.0,1,0.0,0.0,0.0,0.0,1,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,1.0,1.0,0.0,1.0,1.0
4,0,1.0,1,0.0,0.0,1.0,0.0,1,NaN,0.0,...,0.0,1.0,0.0,NaN,NaN,0.0,1.0,1.0,0.0,1.0

In [21]:
imputer = Imputer(missing_values = "NaN" ,strategy = 'most_frequent', axis = 0)

In [22]:
imputer = imputer.fit(nom_x)

In [23]:
nom_x = imputer.transform(nom_x)

In [24]:
nom_x = pd.DataFrame(data = nom_x)

In [25]:
nom_x.columns = ['aa','ab','ac','ad','ae','af','ag','ah','ai','aj','ak','al','am','an','ao','ap','aq','ar','as','at','au','av','aw']

In [26]:
nom_x.head()

,aa,ab,ac,ad,ae,af,ag,ah,ai,aj,...,an,ao,ap,aq,ar,as,at,au,av,aw
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
2,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
3,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0
4,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0

In [27]:
frames = [nom_x,continuous_x]

In [28]:
x_data = pd.concat(frames, axis=1)

In [29]:
x_data.head()

,aa,ab,ac,ad,ae,af,ag,ah,ai,aj,...,q,r,s,t,u,v,w,x,y,z
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.000000,0.104953,0.015291,0.054054,1.0,0.307317,0.003425,0.205357,0.142857,0.198972
1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.162371,0.114149,0.039755,0.047297,0.4,0.229268,0.006849,0.419643,0.261905,0.176233
2,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.071521,0.114149,0.337411,0.027027,0.2,0.058537,0.003425,0.419643,0.293651,0.021525
3,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.010954,0.109040,0.019368,0.094595,1.0,0.317073,0.037671,0.165179,0.134921,0.187892
4,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.100515,0.264345,0.020387,0.125969,1.0,0.073171,0.041096,0.066964,0.134921,0.286547

In [30]:
X_train, X_test, y_train, y_test = train_test_split(x_data,y_value,test_size=0.3, random_state=100)

In [31]:
X_train.columns = ['aa','ab','ac','ad','ae','af','ag','ah','ai','aj','ak','al','am','an','ao','ap','aq','ar','as','at','au','av','aw','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

#x_data.columns = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','aa','ab','ac','ad','ae','af','ag','ah','ai','aj','ak','al','am','an','ao','ap','aq','ar','as','at','au','av','aw']

X_test.columns = ['aa','ab','ac','ad','ae','af','ag','ah','ai','aj','ak','al','am','an','ao','ap','aq','ar','as','at','au','av','aw','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

In [32]:
X_train.columns

Index(['aa', 'ab', 'ac', 'ad', 'ae', 'af', 'ag', 'ah', 'ai', 'aj', 'ak', 'al',
       'am', 'an', 'ao', 'ap', 'aq', 'ar', 'as', 'at', 'au', 'av', 'aw', 'a',
       'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
       'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='object')

In [33]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.

In [34]:
classifier = Sequential()

In [35]:
classifier.add(Dense(output_dim = 25, init = 'uniform', activation = 'relu', input_dim = 49))

C:\Users\USER\Anaconda3\envs\keras_env\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=49, units=25, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [36]:
classifier.add(Dense(output_dim = 25, init = 'uniform', activation = 'relu'))

C:\Users\USER\Anaconda3\envs\keras_env\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=25, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [37]:
classifier.add(Dense(output_dim = 25, init = 'uniform', activation = 'relu'))

C:\Users\USER\Anaconda3\envs\keras_env\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=25, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [38]:
#classifier.add(Dense(output_dim = 25, init = 'uniform', activation = 'relu'))

In [39]:
classifier.add(Dense(output_dim = 25, init = 'uniform', activation = 'relu'))

C:\Users\USER\Anaconda3\envs\keras_env\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=25, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [40]:
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\Users\USER\Anaconda3\envs\keras_env\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [41]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [42]:
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\Users\USER\Anaconda3\envs\keras_env\lib\site-packages\keras\models.py:944: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '

Epoch 1/100
1098/1098 [==============================] - 4s 4ms/step - loss: 0.6603 - acc: 0.6066
Epoch 2/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.4977 - acc: 0.7678
Epoch 3/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.3854 - acc: 0.8333
Epoch 4/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.3184 - acc: 0.8789
Epoch 5/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.2713 - acc: 0.9080
Epoch 6/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.2413 - acc: 0.9107
Epoch 7/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.2011 - acc: 0.9189
Epoch 8/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.1287 - acc: 0.9508
Epoch 9/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.0589 - acc: 0.9818
Epoch 10/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.0580 - acc: 0.9818
Epoch 11/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.0341 - acc: 0.9945
Epoch 12/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.0152 - acc: 0.9973
Epoch 13/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.0053 - acc: 1.0000
Epoch 14/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.0034 - acc: 1.0000
Epoch 15/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.0019 - acc: 1.0000
Epoch 16/100
1098/1098 [==============================] - 1s 1ms/step - loss: 0.0012 - acc: 1.0000
Epoch 17/100
1098/1098 [==============================] - 1s 1ms/step - loss: 9.0071e-04 - acc: 1.0000
Epoch 18/100
1098/1098 [==============================] - 1s 1ms/step - loss: 6.7083e-04 - acc: 1.0000
Epoch 19/100
1098/1098 [==============================] - 1s 1ms/step - loss: 5.0075e-04 - acc: 1.0000
Epoch 20/100
1098/1098 [==============================] - 1s 1ms/step - loss: 3.9824e-04 - acc: 1.0000
Epoch 21/100
1098/1098 [==============================] - 1s 1ms/step - loss: 3.1486e-04 - acc: 1.0000
Epoch 22/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.5300e-04 - acc: 1.0000
Epoch 23/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.0383e-04 - acc: 1.0000
Epoch 24/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.6725e-04 - acc: 1.0000
Epoch 25/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.4048e-04 - acc: 1.0000
Epoch 26/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1595e-04 - acc: 1.0000
Epoch 27/100
1098/1098 [==============================] - 1s 1ms/step - loss: 9.6662e-05 - acc: 1.0000
Epoch 28/100
1098/1098 [==============================] - 1s 1ms/step - loss: 8.1300e-05 - acc: 1.0000
Epoch 29/100
1098/1098 [==============================] - 1s 1ms/step - loss: 6.8784e-05 - acc: 1.0000
Epoch 30/100
1098/1098 [==============================] - 1s 1ms/step - loss: 5.8228e-05 - acc: 1.0000
Epoch 31/100
1098/1098 [==============================] - 1s 1ms/step - loss: 4.9641e-05 - acc: 1.0000
Epoch 32/100
1098/1098 [==============================] - 1s 1ms/step - loss: 4.2132e-05 - acc: 1.0000
Epoch 33/100
1098/1098 [==============================] - 1s 1ms/step - loss: 3.6316e-05 - acc: 1.0000
Epoch 34/100
1098/1098 [==============================] - 1s 1ms/step - loss: 3.0928e-05 - acc: 1.0000
Epoch 35/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.6676e-05 - acc: 1.0000
Epoch 36/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.2835e-05 - acc: 1.0000
Epoch 37/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.9916e-05 - acc: 1.0000
Epoch 38/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.7074e-05 - acc: 1.0000
Epoch 39/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.4805e-05 - acc: 1.0000
Epoch 40/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.2802e-05 - acc: 1.0000
Epoch 41/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1208e-05 - acc: 1.0000
Epoch 42/100
1098/1098 [==============================] - 1s 1ms/step - loss: 9.7124e-06 - acc: 1.0000
Epoch 43/100
1098/1098 [==============================] - 1s 1ms/step - loss: 8.4673e-06 - acc: 1.0000
Epoch 44/100
1098/1098 [==============================] - 1s 1ms/step - loss: 7.3303e-06 - acc: 1.0000
Epoch 45/100
1098/1098 [==============================] - 1s 1ms/step - loss: 6.4029e-06 - acc: 1.0000
Epoch 46/100
1098/1098 [==============================] - 1s 1ms/step - loss: 5.5566e-06 - acc: 1.0000
Epoch 47/100
1098/1098 [==============================] - 1s 1ms/step - loss: 4.8747e-06 - acc: 1.0000
Epoch 48/100
1098/1098 [==============================] - 1s 1ms/step - loss: 4.2503e-06 - acc: 1.0000
Epoch 49/100
1098/1098 [==============================] - 1s 1ms/step - loss: 3.7321e-06 - acc: 1.0000
Epoch 50/100
1098/1098 [==============================] - 1s 1ms/step - loss: 3.2369e-06 - acc: 1.0000
Epoch 51/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.8504e-06 - acc: 1.0000
Epoch 52/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.5110e-06 - acc: 1.0000
Epoch 53/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.2048e-06 - acc: 1.0000
Epoch 54/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.9353e-06 - acc: 1.0000
Epoch 55/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.7127e-06 - acc: 1.0000
Epoch 56/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.5045e-06 - acc: 1.0000
Epoch 57/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.3325e-06 - acc: 1.0000
Epoch 58/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1758e-06 - acc: 1.0000
Epoch 59/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.0412e-06 - acc: 1.0000
Epoch 60/100
1098/1098 [==============================] - 1s 1ms/step - loss: 9.2614e-07 - acc: 1.0000
Epoch 61/100
1098/1098 [==============================] - 1s 1ms/step - loss: 8.1809e-07 - acc: 1.0000
Epoch 62/100
1098/1098 [==============================] - 1s 1ms/step - loss: 7.2763e-07 - acc: 1.0000
Epoch 63/100
1098/1098 [==============================] - 1s 1ms/step - loss: 6.5311e-07 - acc: 1.0000
Epoch 64/100
1098/1098 [==============================] - 1s 1ms/step - loss: 5.8187e-07 - acc: 1.0000
Epoch 65/100
1098/1098 [==============================] - 1s 1ms/step - loss: 5.2434e-07 - acc: 1.0000
Epoch 66/100
1098/1098 [==============================] - 1s 1ms/step - loss: 4.6993e-07 - acc: 1.0000
Epoch 67/100
1098/1098 [==============================] - 1s 1ms/step - loss: 4.2504e-07 - acc: 1.0000
Epoch 68/100
1098/1098 [==============================] - 1s 1ms/step - loss: 3.8610e-07 - acc: 1.0000
Epoch 69/100
1098/1098 [==============================] - 1s 1ms/step - loss: 3.4973e-07 - acc: 1.0000
Epoch 70/100
1098/1098 [==============================] - 1s 1ms/step - loss: 3.1784e-07 - acc: 1.0000
Epoch 71/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.9100e-07 - acc: 1.0000
Epoch 72/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.6714e-07 - acc: 1.0000
Epoch 73/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.4713e-07 - acc: 1.0000
Epoch 74/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.2677e-07 - acc: 1.0000
Epoch 75/100
1098/1098 [==============================] - 1s 1ms/step - loss: 2.1272e-07 - acc: 1.0000
Epoch 76/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.9795e-07 - acc: 1.0000
Epoch 77/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.8635e-07 - acc: 1.0000
Epoch 78/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.7559e-07 - acc: 1.0000
Epoch 79/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.6695e-07 - acc: 1.0000
Epoch 80/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.5885e-07 - acc: 1.0000
Epoch 81/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.5233e-07 - acc: 1.0000
Epoch 82/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.4590e-07 - acc: 1.0000
Epoch 83/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.4100e-07 - acc: 1.0000
Epoch 84/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.3678e-07 - acc: 1.0000
Epoch 85/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.3372e-07 - acc: 1.0000
Epoch 86/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.3007e-07 - acc: 1.0000
Epoch 87/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.2665e-07 - acc: 1.0000
Epoch 88/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.2412e-07 - acc: 1.0000
Epoch 89/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.2180e-07 - acc: 1.0000
Epoch 90/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.2042e-07 - acc: 1.0000
Epoch 91/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1938e-07 - acc: 1.0000
Epoch 92/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1654e-07 - acc: 1.0000
Epoch 93/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1564e-07 - acc: 1.0000
Epoch 94/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1521e-07 - acc: 1.0000
Epoch 95/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1489e-07 - acc: 1.0000
Epoch 96/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1342e-07 - acc: 1.0000
Epoch 97/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1303e-07 - acc: 1.0000
Epoch 98/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1273e-07 - acc: 1.0000
Epoch 99/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1270e-07 - acc: 1.0000
Epoch 100/100
1098/1098 [==============================] - 1s 1ms/step - loss: 1.1248e-07 - acc: 1.0000

In [43]:
#classifier.fit(X_test, y_test, batch_size = 5, nb_epoch = 100)

# Creating the confusion matrix

In [44]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [45]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [46]:
cm

array([[167,   0],
       [  0, 304]], dtype=int64)

In [47]:
((cm[0][0]+cm[1][1])/(cm[1][0]+cm[1][1]+cm[0][0]+cm[0][1]))*100

100.0

In [48]:
#y_pred

In [49]:
#y_test